#!/bin/bash

# Exit codes
EX_MOUNT=79		# Something wrong with the mounted volume
EX_LOG=80		# Log directory or file couldn't be created
EX_FD=81		# No free filedescriptors left or problems using the next free one
EX_FUNC=82		# Global functions could not be loaded
EX_USUAGE=64	# Probably parameters missing
EX_NOINPUT=66
EX_CANTCREAT=73

# Local vars

# debugswitch can be set in two different ways. either
# debugswitch=true source $0
# or you set it 

if [[ -z $debugswitch ]]; then
	debugswitch=false
fi

$debugswitch && echo "debugswitch was set to on"

######################### Node context #########################

CONTENT="/opt/individual_content"
if [[ ! -d "$CONTENT" ]]; then
	mkdir -p "$CONTENT"
	if [[ $? != 0 ]]; then
		exit $EX_MOUNT
	fi
fi

# Get a hostname to integer $1
function nodestring {
	if [ ! -z "$1" ]; then
		local nodestr="node"
		if [ "$1" -lt 10 ]; then
			nodestr=""$nodestr"0"
		fi
		nodestr="$nodestr$1"
		echo $nodestr
	else
		$debugswitch && echo "Invalid usage of nodestring function"
		exit $EX_USAGE
	fi
}


######################### Global context #########################

function test_node_str {
	local regex='^node[0-9]{1,2}$'
	if [[ "$1" =~ $regex ]]; then
		return 0
	else
		return 1
	fi
}


# A Map for the Zero modules: hostname -> ip address
declare -A ZEROS

# Returns an ipaddress for a zero module. $1 hostname
function get_zero_ip {
	
	test_node_str $1
	if [[ $? != 0  ]]; then
		$debugswitch && echo "Provided nodestring to node function was not valid"
		return 1
	fi
	
	if [[ -z "${ZEROS[$1]+unset}" ]]; then
		$debugswitch && echo "There was no ip generated for $1. Maybe it is not a zero module?"
		return 1;
	else
		echo "${ZEROS[$1]}"
	fi

}

# Returns a valid ip from hostname. $1 = geographical position of node
function get_ip_for_node {
	i=$1
	if [[ $i -gt 16 && $i -lt 23 || $i -gt 23 && $i -lt 30 ]]; then
		nodename=$(nodestring $i)
		ip=$(get_zero_ip "$nodename")
		identifier="Zero Module"
	else
		ip=$IP_PATTERN_R3$i
		identifier="R3 Module"
	fi
	
	echo $ip
	
}

# Globals
IP_PATTERN_R3="10.42.0."
IP_PATTERN_ZERO="192.168.1."

# Generate the zero ips $(seq 17 29)
z=121
for i in {17..22} {24..29}; do

	ip="$IP_PATTERN_ZERO$z"
	node=$(nodestring $i)
	
	$debugswitch && echo "Generating $ip for $node"
	ZEROS[$node]=$ip
	if [[ $i -eq 22 ]]; then
		z=$(( z + 2 ))
	else 
		z=$(( z + 1 ))
	fi
	
	
done

######################### Servermodule context #########################

# Looks for a free file descriptor and returns it. If none is found returns -1.
function find_free_fd {
	found=-1
	for fd in $(seq 0 200); do
    	[[ ! -e /proc/$$/fd/${fd} ]] && found=${fd} && break
	done
	echo $found
}

function register_run {
	echo "hallo"
}