#!/bin/bash
### BEGIN INIT INFO
# Provides:          client nfs mount
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable services provided by daemon.
### END INIT INFO

/bin/bash /opt/mount_content.sh start
